name: final_coffee
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.2.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  lottie: ^2.6.0
  zoom_tap_animation: ^1.1.0
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  permission_handler: ^11.0.1
  firebase_app_check: ^0.2.0+1
  firebase_auth: ^4.10.1
  cached_network_image: ^3.3.0
  path_provider: ^2.1.1
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/cof_logo.jpg"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/svg/
     - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Regular.ttf
           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
